language: node_js
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
sudo: false
script:
  - npm test
  - if [[ $TRAVIS_NODE_VERSION == "4" ]]; then npm run docs:build; fi
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./node_modules/.bin/git-update-ghpages -e; fi
env:
  global:
    - CC=clang CXX=clang++ npm_config_clang=1
    - GIT_NAME: Travis CI
    - GIT_EMAIL: nobody@nobody.org
    - GITHUB_REPO: rstacruz/pnpm
    - GIT_SOURCE: _docpress
