language: node_js
node_js:
  - 4
  - 6
  - 8
  - 10
git:
  depth: 5
sudo: false
before_install:
  - npm set verify-store-integrity false
  - git fetch --unshallow
  - curl -L https://unpkg.com/@pnpm/self-installer | PNPM_VERSION=1.33.2 node
  # Testing whether pnpm can upgrade itself
  - pnpm i -g pnpm@next
  - pnpm -v
install:
  - pnpm recursive link --no-lock
script:
  - /bin/bash lint-commits.sh
  - ./node_modules/.bin/commitlint --from=$TRAVIS_COMMIT
  - npm t --prefix packages/supi
  - npm t --prefix packages/pnpm
env:
  global:
    - CC=clang CXX=clang++ npm_config_clang=1
    - GIT_NAME: Travis CI
    - GIT_EMAIL: nobody@nobody.org
    - GITHUB_REPO: pnpm/pnpm
notifications:
  email: false
