environment:
  matrix:
    - nodejs_version: 10
install:
  - ps: Install-Product node $env:nodejs_version
  - npm set verify-store-integrity false
  - set PNPM_VERSION=next
  - curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
  - pnpm -v
  - pnpm recursive install --no-lock
matrix:
  fast_finish: true
build: off
version: '{build}'
test_script:
  - node --version
  - pnpm --version
  - IF %APPVEYOR_REPO_BRANCH%==master pnpm run test-master
  - IF NOT %APPVEYOR_REPO_BRANCH%==master pnpm run test-branch
skip_tags: true
cache:
  - storage
