environment:
  matrix:
    - nodejs_version: 10
install:
  - ps: Install-Product node $env:nodejs_version
  - npm set verify-store-integrity false
  - set PNPM_VERSION=next
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm -v
  - pnpm recursive install --no-lock
matrix:
  fast_finish: true
build: off
version: '{build}'
test_script:
  - node --version
  - pnpm --version
  - pnpm t
skip_tags: true
