blank_issues_enabled: false
contact_links:
  - name: Question ğŸ¤·ğŸ»â€â™‚ï¸
    url: https://github.com/pnpm/pnpm/discussions/new?category=q-a
    about: Ask questions and discuss with other community members
  - name: Chat ğŸ˜
    url: https://r.pnpm.io/chat
    about: For a quick question you should do it through our community chat