name: CI

on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.platform }}-${{ matrix.node }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        node:
          - '18.12'
          - '20'
          - '22'
        platform:
          - ubuntu-latest
          - windows-latest

    name: '${{matrix.platform}} / Node.js ${{ matrix.node }}'
    runs-on: ${{matrix.platform}}

    steps:
    - name: Configure Git
      run: |
        git config --global core.autocrlf false
        git config --global user.name "xyz"
        git config --global user.email "x@y.z"
    - name: Checkout Commit
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Install pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        standalone: true
    - name: Setup Node
      run: pnpm env use -g ${{ matrix.node }}
    - name: Install npm@8
      run: pnpm add --global npm@8
    - name: pnpm install
      run: pnpm install
    # - name: Cache TypeScript and Jest
      # uses: actions/cache@v3
      # with:
        # path: |
          # packages/*/lib
          # packages/*/tsconfig.tsbuildinfo
          # privatePackages/*/lib
          # privatePackages/*/tsconfig.tsbuildinfo
          # .jest-cache
          # .verdaccio-cache
        # key: ts-jest-${{ matrix.platform }}-${{ matrix.node }}-${{ github.run_id }}
        # restore-keys: ts-jest-${{ matrix.platform }}-${{ matrix.node }}-
    - name: run tests (main)
      timeout-minutes: 60
      if: github.ref == 'refs/heads/main'
      run: pnpm run test-main
      env:
        PNPM_WORKERS: 3
    - name: run tests (branch)
      timeout-minutes: 60
      if: github.ref != 'refs/heads/main'
      run: pnpm run test-branch
      env:
        PNPM_WORKERS: 3
